site_name: Parker Erickson
nav:
  - 'Home': index.md
  - 'Projects': projects.md
  - 'Blog':
    - 'Continuous Deployment for MkDocs with GitHub Actions': blog/MkDocsCD.md
    - 'Getting Started with MkDocs': blog/gettingStartedWithMkdocs.md
    - 'IPO Prediction Using Graph Convolutional Neural Networks': blog/ipoGCN.md
    - 'Do You Really Need Trash Cans?': blog/doYouReallyNeedTrashCans.md

theme:
  name: material
  logo: https://avatars1.githubusercontent.com/u/9616171?s=460&v=4
  favicon: https://avatars1.githubusercontent.com/u/9616171?s=460&v=4

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/parkererickson
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/p_erickson30
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/parker-erickson
    - icon: fontawesome/brands/medium
      link: https://medium.com/@parker.erickson

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - pdf-export
