name: Build Documentation using MkDocs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python3 -m pip3 install --U pip
          pip3 install mkdocs-material
          mkdocs gh-deploy

